### PR TITLE
Add scripts to ensure Theorem 9.5 remains sorry-free #37

### PR DESCRIPTION
**Pull request by bentoner**
This pull request adds the script but doesn't yet integrate it into CI.

### CODE REVIEW

**Comment by jcommelin** [comment]
Thanks a lot! Could you please add a step to the CI actions so that it runs the python script?

**Comment by bentoner** [comment]
> Thanks a lot! Could you please add a step to the CI actions so that it runs the python script?

It's not easy to turn on just this as the action is in separate repository https://github.com/leanprover-contrib/lean-build-action - I didn't want to pull that in-tree just to replace it to enable having an olean cache. So I turn this on in CI in the dependent pull request https://github.com/leanprover-community/lean-liquid/pull/45 .

**Comment by bentoner** [comment]
I forgot to ask exactly what I should be checking is sorry-free. It's currently `thm95.thm95''` but maybe it's supposed to be `liquid.first_target`?

**Comment by jcommelin** [comment]
@bentoner It doesn't matter too much because I don't think a `sorry` will be introduced in the short path from `thm95.thm95''` to `first_target`. But maybe it is a bit more natural to check that `first_target` remains sorry free.

**Comment by bentoner** [comment]
Okay, updated to check `first_target` instead.

**Comment by jcommelin** [comment]
Superseded by #45.

**Pull request closed without merging**
